[window]
samples = 2
fullscreen = true
vsync = true
dimensions = [640, 480]

[audio]
jump_volume = 0.5
wall_volume = 0.5
gong_volume = 0.5

wall_max_intensity = 8.0
wall_min_intensity = 2.0

[gameplay]
gravity = 15.0
impulse = 25.0
reset = true
damping = 0.5
ball_radius = 0.5
set_mouse = false
set_unlimited = false

[camera]
zoom = 0.03

[graphics]
background_color = [1.0, 1.0, 1.0, 1.0]
ball_color = [0.0, 0.0, 0.0, 1.0]
wall_color = [0.0, 0.0, 0.0, 1.0]
cursor_color = [1.0, 0.0, 0.0, 1.0]
effect_color = [1.0, 0.0, 0.0, 1.0]

cursor_inner_radius = 0.00001
cursor_outer_radius = 0.00002
cursor_thickness = 0.000005

effect_timer = 0.8
effect_thickness = 0.4

[event_loop]
ups = 60
max_fps = 60

[control]
mouse_sensibility = 0.005

[physics]
unit = 5.0
